package MeetingApp;
// Generated 12/03/2017 11:53:04 م by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Meeting generated by hbm2java
 */
public class Meeting  implements java.io.Serializable {


     private Integer meetingId;
     private Host host;
     private String meetingName;
     private String meetingDescription;
     private Date meetingDate;
     private Date meetingTime;
     private String meetingLocation;
     private Set<ParticipantMeeting> participantMeetings = new HashSet<ParticipantMeeting>(0);

    public Meeting() {
    }

	
    public Meeting(Host host, String meetingName, String meetingDescription, Date meetingDate, Date meetingTime, String meetingLocation) {
        this.host = host;
        this.meetingName = meetingName;
        this.meetingDescription = meetingDescription;
        this.meetingDate = meetingDate;
        this.meetingTime = meetingTime;
        this.meetingLocation = meetingLocation;
    }
    public Meeting(Host host, String meetingName, String meetingDescription, Date meetingDate, Date meetingTime, String meetingLocation, Set<ParticipantMeeting> participantMeetings) {
       this.host = host;
       this.meetingName = meetingName;
       this.meetingDescription = meetingDescription;
       this.meetingDate = meetingDate;
       this.meetingTime = meetingTime;
       this.meetingLocation = meetingLocation;
       this.participantMeetings = participantMeetings;
    }
   
    public Integer getMeetingId() {
        return this.meetingId;
    }
    
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }
    public Host getHost() {
        return this.host;
    }
    
    public void setHost(Host host) {
        this.host = host;
    }
    public String getMeetingName() {
        return this.meetingName;
    }
    
    public void setMeetingName(String meetingName) {
        this.meetingName = meetingName;
    }
    public String getMeetingDescription() {
        return this.meetingDescription;
    }
    
    public void setMeetingDescription(String meetingDescription) {
        this.meetingDescription = meetingDescription;
    }
    public Date getMeetingDate() {
        return this.meetingDate;
    }
    
    public void setMeetingDate(Date meetingDate) {
        this.meetingDate = meetingDate;
    }
    public Date getMeetingTime() {
        return this.meetingTime;
    }
    
    public void setMeetingTime(Date meetingTime) {
        this.meetingTime = meetingTime;
    }
    public String getMeetingLocation() {
        return this.meetingLocation;
    }
    
    public void setMeetingLocation(String meetingLocation) {
        this.meetingLocation = meetingLocation;
    }
    public Set<ParticipantMeeting> getParticipantMeetings() {
        return this.participantMeetings;
    }
    
    public void setParticipantMeetings(Set<ParticipantMeeting> participantMeetings) {
        this.participantMeetings = participantMeetings;
    }




}


