package MeetingApp;
// Generated 12/03/2017 11:53:04 م by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Participant generated by hbm2java
 */
public class Participant  implements java.io.Serializable {


     private String participantEmail;
     private String participantName;
     private Set<ParticipantMeeting> participantMeetings = new HashSet<ParticipantMeeting>(0);

    public Participant() {
    }

	
    public Participant(String participantEmail, String participantName) {
        this.participantEmail = participantEmail;
        this.participantName = participantName;
    }
    public Participant(String participantEmail, String participantName, Set<ParticipantMeeting> participantMeetings) {
       this.participantEmail = participantEmail;
       this.participantName = participantName;
       this.participantMeetings = participantMeetings;
    }
   
    public String getParticipantEmail() {
        return this.participantEmail;
    }
    
    public void setParticipantEmail(String participantEmail) {
        this.participantEmail = participantEmail;
    }
    public String getParticipantName() {
        return this.participantName;
    }
    
    public void setParticipantName(String participantName) {
        this.participantName = participantName;
    }
    public Set<ParticipantMeeting> getParticipantMeetings() {
        return this.participantMeetings;
    }
    
    public void setParticipantMeetings(Set<ParticipantMeeting> participantMeetings) {
        this.participantMeetings = participantMeetings;
    }




}


