package MeetingApp;
// Generated 12/03/2017 11:53:04 م by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private int statusId;
     private String statusType;
     private Set<ParticipantMeeting> participantMeetings = new HashSet<ParticipantMeeting>(0);

    public Status() {
    }

	
    public Status(int statusId, String statusType) {
        this.statusId = statusId;
        this.statusType = statusType;
    }
    public Status(int statusId, String statusType, Set<ParticipantMeeting> participantMeetings) {
       this.statusId = statusId;
       this.statusType = statusType;
       this.participantMeetings = participantMeetings;
    }
   
    public int getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(int statusId) {
        this.statusId = statusId;
    }
    public String getStatusType() {
        return this.statusType;
    }
    
    public void setStatusType(String statusType) {
        this.statusType = statusType;
    }
    public Set<ParticipantMeeting> getParticipantMeetings() {
        return this.participantMeetings;
    }
    
    public void setParticipantMeetings(Set<ParticipantMeeting> participantMeetings) {
        this.participantMeetings = participantMeetings;
    }




}


